name: Check for Binary Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-binary-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Get the base and head SHA
      id: vars
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "::set-output name=base::${{ github.event.before }}"
          echo "::set-output name=head::${{ github.sha }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "::set-output name=base::${{ github.event.pull_request.base.sha }}"
          echo "::set-output name=head::${{ github.event.pull_request.head.sha }}"
        fi

    - name: Run check-binary-files action
      id: check-binary-files
      uses: deamen/gh-actions/check-binary-files@8321ae0dadf28c65f7b1e3f42220b8a91d627581
      with:
        base-ref: "3cbfa567c2ca0759b77b85fe2e5946b663ad7f26"
        head-ref: ${{ github.sha }}

    - name: Report result
      if: success() || failure()
      run: |
        if [ -n "${{ steps.check-binary-files.outputs.binary_files }}" ]; then
          echo "Workflow failed due to binary files in the commit history:"
          echo "${{ steps.check-binary-files.outputs.binary_files }}"
        else
          echo "No binary files detected."
        fi
