name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  setup-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        id: version_vars
        run: |
          echo "chk_cert_ver=0.0.3" >> $GITHUB_OUTPUT
          echo "go_version=1.20.12" >> $GITHUB_OUTPUT

    outputs:
      chk_cert_ver: ${{ steps.version_vars.outputs.chk_cert_ver }}
      go_version: ${{ steps.version_vars.outputs.go_version }}

  build-and-upload-chk_cert:
    needs: setup-variables
    uses: ./.github/workflows/chk_cert_base_workflow.yml
    with:
      chk_cert_ver: ${{ needs.setup-variables.outputs.chk_cert_ver }}
      go-version: ${{ needs.setup-variables.outputs.go_version }}

  create-release:
    runs-on: ubuntu-latest
    needs: [setup-variables, build-and-upload-chk_cert]
    steps:
      - name: Download chk_cert release tarball
        uses: actions/download-artifact@v3
        with:
          name: chk_cert-${{ needs.setup-variables.outputs.chk_cert_ver }}.tar.xz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./chk_cert-${{ needs.setup-variables.outputs.chk_cert_ver }}.tar.xz
