name: "Build chk_cert"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  Build-and-upload-openssl-static-1xx:
    uses: ./.github/workflows/chk_cert_base_workflow.yml
    with:
      chk_cert_ver: 0.0.1
      go-version: 1.18.7
