name: "Build chk_cert"

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  Build-and-upload-chk_cert:
    uses: ./.github/workflows/chk_cert_base_workflow.yml
    with:
      chk_cert_ver: 0.0.3
      go-version: 1.20.12
