name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  setup-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        id: version_vars
        run: |
          echo "chk_cert_ver=0.0.3" >> $GITHUB_OUTPUT
          echo "go_version=1.20.12" >> $GITHUB_OUTPUT

    outputs:
      chk_cert_ver: ${{ steps.version_vars.outputs.chk_cert_ver }}
      go_version: ${{ steps.version_vars.outputs.go_version }}

  build-and-upload-chk_cert:
    needs: setup-variables
    uses: ./.github/workflows/chk_cert_base_workflow.yml
    with:
      chk_cert_ver: ${{ needs.setup-variables.outputs.chk_cert_ver }}
      go-version: ${{ needs.setup-variables.outputs.go_version }}

  create-release:
    runs-on: ubuntu-latest
    needs: [setup-variables, build-and-upload-chk_cert]
    steps:
      - name: Download chk_cert release tarball
        uses: actions/download-artifact@v4.1.7
        with:
          name: chk_cert-${{ needs.setup-variables.outputs.chk_cert_ver }}.tar.xz

      - name: Create Release
        id: create_release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          body="Release notes for $tag_name"
          release_tag="${tag_name}"

          echo "Creating release $release_tag"
          gh release create "$release_tag" "chk_cert-${{ needs.setup-variables.outputs.chk_cert_ver }}.tar.xz" --notes "$body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
